### ISSUE TITLE
question regarding confidence of -e norrna option

### ISSUE THREAD

**Issue by caity-s** [hzi-bifo/RiboDetector#23]
Dear Zhi-Luo Deng,

Firstly, thank you for the great tool - I have over 200 100-150M PE metaTs (average length of 125bp) and went from ~14 hours processing per sample with SMR to ~4 hours (using CPU only linux server) on a 90M PE sample with Ribodetector. It is a fantastic improvement on time. rRNA was about 73% (-e norrna), and SMR found 70%, so they agreed quite well.

I just have a question about the -e norrna flag. After processing it seems (after subsetting 100 random sequences from the norrna output file and blasting) 15% are (mainly) eukaryotic rRNA. Based on your manuscript it seems that this proportion of false negatives is kind of expected for divergent sequences - and so maybe something to be expected from wastewater samples with complex microbial communities? It would be great to know what you think - or if you think I should tweak a setting.

Just my observations in general: 3 samples at a time (40 threads each) tends to use around 900GB RAM, with processing 30M taking 1 hour, 72M 6.5 hours, 157M 10.5 hours (some variation likely due to server IO too). Really, I need to get my hands on some GPUs - it would be great to see how much faster it would be.

I am using gnu parallel to run 2 jobs at a time, as the memory limit was getting a bit marginal for 3 on our 1TB server. Though perhaps it would be better to run 1 job at a time with 120t instead....

`parallel --joblog parallel_logfile2 -j2 ribodetector_cpu -t 60 -l 100 -i {}_R1_fastp.fastq.gz {}_R2_fastp.fastq.gz -e norrna -o {}_mRNA_R1.fq {}_mRNA_R2.fq -r {}_rRNA_R1.fq {}_rRNA_R2.fq '&>' {}_log.txt`

Thank you,
Caitlin

**Comment by dawnmy** [comment]
Great to hear that RiboDetector works well for you. And thank you for sharing your observations. `-e norrna` should be less strict in terms of classifying a reads as rRNA, which means it will predict more rRNA reads (slightly higher FPs but lower FNs) compared to `-e rrna` and `-e none`. 

> I just have a question about the -e norrna flag. After processing it seems (after subsetting 100 random sequences from the norrna output file and blasting) 15% are (mainly) eukaryotic rRNA.

Did you performed QC step to trim remaining adaptor sequences and bad quality bases before you run it? Do you know which types of rRNA are they? Are they spacer sequences in between two rRNAs? Could you send me some example sequences that I can take a look. 

Since you have so large input file, I would suggest you to set the `--chunk_size` parameter in version 0.2.6 to reduce the memory use. 

Yes, running two jobs in parallel may not be faster than one job with doubled threads number because of the RAM and IO limit.  

With GPU you will see substantial speedup. 😁

**Comment by caity-s** [comment]
Thank you for the great tips! I will try chunk size for sure - and push for some GPU! Again, it is hard to convey how grateful I am to find this software :D

Yes, we did quite thorough QC with fastp beforehand, and length requirement of >50 (but average read length is ~125). Could well be spacer sequences (some likely ITS based on the blast annotation), and there are some unexpected funky things with rRNA. I'll put the blast annotation so you can see. This is 15 seqs out of the 100 subsample I blasted.

```Uncultured bacterium clone F5K2Q4C04H8MYB 23S ribosomal RNA gene, partial sequence
Uncultured eukaryote clone F5K2Q4C04IL8TG 28S ribosomal RNA gene, partial sequence
Lumbriculus sp. EEZ-2018 isolate ANN_LUMva large subunit ribosomal RNA gene, partial sequence
uncultured fungus genomic DNA sequence contains 18S rRNA gene, ITS1, 5.8S rRNA gene, ITS2, 28S rRNA gene, isolate consensus02618
Epistylis sp. ZhW-2019a isolate Hubei large subunit ribosomal RNA gene, partial sequence
Epistylis sp. 1 JI2016080701 large subunit ribosomal RNA gene, partial sequence
Uncultured eukaryote clone F5K2Q4C04IQ1G9 28S ribosomal RNA gene, partial sequence
Uncultured eukaryote clone F5K2Q4C04JA1DB 28S ribosomal RNA gene, partial sequence
Uncultured soil fungus clone NCD_LSU_otu464 28S ribosomal RNA gene, partial sequence
Aspidisca lynceus isolate LCY2015101602 small subunit ribosomal RNA gene, partial sequence
uncultured fungus genomic DNA sequence contains 18S rRNA gene, ITS1, 5.8S rRNA gene, ITS2, 28S rRNA gene, isolate consensus02618
Uncultured eukaryote clone F5K2Q4C04I8OUX 28S ribosomal RNA gene, partial sequence
Epistylis chrysemydis large subunit ribosomal RNA gene, partial sequence
Rotaria rotatoria isolate IT.3 28S ribosomal RNA gene, partial sequence
Uncultured eukaryote clone F5K2Q4C04JX6UB 28S ribosomal RNA gene, partial sequence
```
I have attached the subsample sequences too if they are useful (they are in fasta format, but had to change to .txt to upload it).

Thanks a lot,
Caitlin

[sub_0002_mRNA_R1.txt](https://github.com/hzi-bifo/RiboDetector/files/9300051/sub_0002_mRNA_R1.txt)

**Comment by dawnmy** [comment]
Hi Caitlin,

Thank you for the reads file. I blastn them against ncbi rRNA and ITS database, and only one sequence was similar to rRNA/ITS. With NR database in ncbi, I see the similar output as you posted, most of the matched sequences are annotated as partial rRNA sequences from uncultured eukaryotes. 

I assume either those annotations are doubtable or they are from uncharacterized taxa with rRNA sequences divergent to the curated/well annotated rRNA sequences. But it is very unlikely that most of them are rRNAs since rRNA sequences should be rather conserved usually with divergence <=30% in different taxa. Therefore, I think you can just proceed with the norrna output from RiboDetector for functional profiling. 

Best,
Zhi-Luo

**Comment by caity-s** [comment]
Dear Zhi-Luo,

Sorry for the delayed reply (I was at ISME). Brilliant, thank you so much for looking into it! And thanks again for saving me several weeks of time 😄 

Kind regards,
Caitlin
