### ISSUE TITLE
Using RiboDetector on assembled contigs? 

### ISSUE THREAD

**Issue by natashagriffin** [hzi-bifo/RiboDetector#24]
Hi there! Thank you for making this awesome tool!

I have a (maybe silly) question: Could I use RiboDetector on a file containing assembled metatranscriptomic contigs (lengths between 200-1600nt)? 

I know it's more normal to remove rRNA pre-assembly, but my lab's existing workflow keeps rRNA in because we usually upload assembled metagenomes/transcriptomes to IMG and let the JGI pipeline take care of ncRNAs and annotation. I'm trying to build part of a new pipeline and unfortunately didn't remove rRNA beforehand (and would rather not have to re-assemble since it took a really long time).

Thanks in advance for any advice/help, I really appreciate it!

**Comment by dawnmy** [comment]
Hi Natasha, thank you for trying RiboDetector. Yes, it can be also used for detecting assembled rRNA sequences from (meta-)transcriptome data. You can set a larger `-l` parameter like `300`. It will work perfectly if the assembled rRNA is not a chimera.

But note that it will not work for identifying rRNAs from assembled metagenome data because the contigs containing rRNA may also have other neighboring genes/sequences.

**Comment by natashagriffin** [comment]
That makes sense, thanks for the explanation! Perfect, I will try it out today.
