### ISSUE TITLE
ValueError:you are required to explicitly set the providers parameter when instantiating InferenceSession

### ISSUE THREAD

**Issue by Abelcanc3rhack3r** [hzi-bifo/RiboDetector#42]
Hi, I installed the Ribodetector on amazon EC2 instance t3.2xlarge

AMI: amazon/amzn2-x86_64-MATEDE_DOTNET-2022.08.31.

The following libraries were used:
conda install pytorch (latest version, pytorch 2.01).   v1.10.2 cannot be installed using conda.

When running the ribodetector on CPU mode:
ribodetector_cpu -t 20 \
  -l 100 \
  -i ./test_mixture_rrna.fasta \
  -e rrna \
  --chunk_size 256 \
  -o ./rna_filter.fasta

I got this error.
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

No idea what its saying, can you help me?

Thanks

**Comment by dawnmy** [comment]
Hi, thank you for reporting this. It seems that the error is because a newer version of onnxruntime is installed in your environment and it requires providers setting. We will update to fix the issue with newer version of onnxruntime. If you need to use it now, you can install a older version of onnxruntime, e.g. with pip: `pip install onnxruntime==1.8.2` or with conda: `conda install onnxruntime==1.7.2`
